### ISSUE TITLE
Build management

### ISSUE THREAD

**Issue by gedl** [DiceTechnology/dice-where#4]
Decide and implement on a build management strategy both for internal cycles and maven central publishing

**Comment by fifol-img** [comment]
Blockers:
- website with description and example usages for the library, example: http://commons.apache.org/proper/commons-math/
- [required license info in pom file, blocked by issue #5 ](https://github.com/DiceTechnology/dice-where/issues/5)
- Currently GPG signature is not working, due to issues with loading on Travis

**Comment by lcardito** [comment]
Should we include the maven wrapper as part of this one? https://github.com/takari/maven-wrapper

**Comment by fifol-img** [comment]
Currently we have integrated with Bintray and released 1.0.0 version there.  We can close this ticked and proceed with Maven Central in another one.
